cJake/etr 952 embed data roles in ciphertext nodejs sdk
evervault/evervault-node pull request #145
Opened 2023-10-13 12:31 UTC by jakekgrog

# Why
Data roles need to be embedded in the ciphertext.

# How

- Embed the data role in the ciphertext
- Perform KDF on the new version with Secp256k1 curve
- Add curve parameters for Secp256k1 curve

2023-10-23 20:23 UTC, boilsquid commented on lib/core/crypto.js
> +    }
Extract to a method, return a Buffer, write a test

2023-10-23 20:42 UTC, boilsquid commented on lib/core/crypto.js
> +    }
![This is the way](https://media2.giphy.com/media/stnjSj2vpLcM4rwmEH/giphy.gif?cid=6104955epjyxn1dg96dgujogx38szm75bwmrp46p0rbumc11&ep=v1_gifs_translate&rid=giphy.gif&ct=g)

2023-10-26 14:39 UTC, jeremywagemans commented on .changeset/many-hairs-bathe.md
> +Add data roles
We really need to polish our changelogs. I'm suggesting updating this with:
```
The `encrypt` function has been enhanced to accept an optional Data Role. This role, once specified, is associated with the data upon encryption. Data Roles can be created in the Evervault Dashboard (Data Roles section) and provide a mechanism for setting clear rules that dictate how and when data, tagged with that role, can be decrypted.
evervault.encrypt('hello world!', 'allow-all');
```

2023-10-26 14:41 UTC, jeremywagemans commented on lib/index.js
> +  async encrypt(data, metadata) {
Signature should be `encrypt(data: Any, role: String?)`

2023-10-26 14:42 UTC, jeremywagemans commented on lib/index.js
> +  async encrypt(data, metadata) {
Also could we validate the role? 

```
    const dataRoleRegex = /^[a-z0-9-]{1,20}$/;
    if (role != null && !dataRoleRegex.test(role)) {
      throw new Error('The provided Data Role slug is invalid. The slug can be retrieved in the Evervault dashboard (Data Roles section).');
    }
    ```

2023-10-26 14:45 UTC, jeremywagemans requested changes
I added a few suggestions.

A few things are also missing:
- We need to update the end to end tests to validate the encrypt function with data role. I would add encrypt data with the `permit-all` data role (already available in the SDK Tests app).
- We need to ensure the forbidden decryption error is handled correctly. I would add an test case for that in our E2E tests as well (encrypt with `forbid-all` data role).
- Roles are not embedded for files. We need to add E2E test cases for that as well.

2023-10-27 10:10 UTC, jeremywagemans approved these changes
🚢 it!

2023-10-27 10:25 UTC, merged