[ETR-2357] Add createEnclaveHttpsAgent for attesting connections to enclave
evervault/evervault-node pull request #195
Opened 2024-07-15 14:13 UTC by donaltuohy

# Why

Add a short description about this PR.
Add links to issues, tech plans etc.

# How

Describe how you've approached the problem

2024-07-15 21:47 UTC, boilsquid requested changes

2024-07-15 21:47 UTC, boilsquid commented on lib/utils/attest.js
> +    if (hostname.endsWith(this.agent.config.enclavesHostname)) {
```suggestion
    if (hostname.endsWith(this.config.enclavesHostname)) {
```

2024-07-15 22:32 UTC, donaltuohy commented on lib/utils/attest.js
> +    if (hostname.endsWith(this.agent.config.enclavesHostname)) {
Updated

2024-07-16 10:39 UTC, hanneary approved these changes

2024-07-16 12:20 UTC, boilsquid approved these changes

2024-07-16 13:18 UTC, merged