Make node SDK pull cert from ca.evervault.com
evervault/evervault-node pull request #47
Opened 2021-06-14 10:29 UTC by davidnugent2425

# Why
The certs only last one year. Including a cert in the package would lead to that version breaking after a year

# How
Download cert from ca.evervault.com

2021-06-14 10:30 UTC, shanecurran requested changes
Should do this over HTTPS to avoid MITM

2021-06-14 12:21 UTC, eoinboylan submitted a review, later dismissed

2021-06-14 14:53 UTC, eoinboylan approved these changes

2021-06-15 09:11 UTC, shanecurran approved these changes
👌

2021-06-15 09:15 UTC, merged

2021-06-15 09:16 UTC, shanecurran commented
:tada: This PR is included in version 1.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@evervault/sdk/v/1.3.1)
- [GitHub release](https://github.com/evervault/evervault-node/releases/tag/v1.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: