feat: add option for p256 curve while defaulting to secp256k1 curve
evervault/evervault-node pull request #72
Opened 2022-01-20 15:12 UTC by jakekgrog

# Why

- Allow users to add a `curve` to client configuration options. Default to `secp256k1` if no curve is provided for backwards compatibility. 
- We will need to send a note (in whatever form) to customers to let them know we're moving to a new curve in the future

# How

Describe how you've approached the problem

# Checklist

- [x] Commit messages are formatted as per [the convention](https://www.conventionalcommits.org/en/v1.0.0/), and breaking changes are marked

2022-01-20 15:29 UTC, eoinboylan requested changes

2022-01-20 15:29 UTC, eoinboylan commented on lib/config.js
> +    secp256r1: {
```suggestion
    prime256v1: {
```

2022-01-20 15:44 UTC, eoinboylan submitted a review, later dismissed

2022-01-24 15:14 UTC, lfarrel6 commented on lib/index.js
> +    this.crypto = Crypto(this.config.encryption[curve], this.http);
do we have any validation on the curves? Would also be good to expose as a constant from the library

2022-02-03 14:34 UTC, merged

2022-02-03 14:35 UTC, shanecurran commented
:tada: This PR is included in version 1.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@evervault/sdk/v/1.10.0)
- [GitHub release](https://github.com/evervault/evervault-node/releases/tag/v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: